# Identidad del microservicio
server.port=8086
spring.application.name=ms-pagos

# Conexión a la base de datos en Laragon (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/RentaCar
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA para MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Registro en el servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/